[package]
name = "test_crate_hello_world_cp"
version = "0.1.0"
authors = ["mengya <zhang.9407@osu.edu>"]

description = "A Simple Hello World Crate"

repository = "https://github.com/MiaZmy1221/test_crate_hello_world.git"

keywords = ["hello", "world"]

